#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /authentication_token
  methods: ['POST']

homepage:
  path: /
  controller: App\Controller\HomeController::home
