##################################
App\Entity\Folder\FolderTpl:
  attributes:
    denormalization_context:
      groups:
        - 'FolderTpl:Update'
        - 'Label'
        - 'Description'
        - 'State'
    normalization_context:
      groups:
        - 'FolderTpl:Read'
        - 'Resource'
        - 'Label'
        - 'Description'

    output: App\Entity\Folder\FolderTpl
    input: App\Entity\Folder\FolderTpl

  collectionOperations:
    get:
      security: is_granted('ROLE_User') or is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
      normalization_context:
        groups:
          - 'FolderTpl:Read'
          - 'Resource'
          - 'Label'
          - 'Description'
        preserve_empty_objects: true
        skip_null_values: false
    post:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

    getexpectation:
      method: GET
      path: /folder_tpls/expectation
      security: is_granted('ROLE_Dashboard')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Get folders submission expectation'
        parameters:
          - name: fromdate
            in: query
            description: 'beginning of date interval'
            required: false
            schema:
              type: string
          - name: todate
            in: query
            description: 'end of date interval'
            required: false
            schema:
              type: string
      normalization_context:
        groups:
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'FolderTpl:Expectation'

    all:
      method: GET
      path: /folder_tpls/all
      security: is_granted('ROLE_User') or is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Get all templates, even out of period'

    periods:
      method: GET
      path: /folder_tpls/periods
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Get folders periods'
        parameters:
          - name: fromdate
            in: query
            description: 'beginning of date interval'
            required: false
            type: string
          - name: todate
            in: query
            description: 'end of date interval'
            required: false
            type: string

      normalization_context:
        groups:
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'FolderTpl:Periods'
        skip_null_values: false

  itemOperations:
    delete:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
      normalization_context:
        groups:
          - 'FolderTpl:Read'
          - 'Resource'
          - 'Label'
          - 'Description'
        preserve_empty_objects: true
        skip_null_values: false
    patch:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    getexpectation:
      method: GET
      path: /folder_tpls/{id}/expectation
      security: is_granted('ROLE_Dashboard')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Get folders submission expectation'
        parameters:
          - name: fromdate
            in: query
            description: 'beginning of date interval'
            required: false
            type: string
          - name: todate
            in: query
            description: 'end of date interval'
            required: false
            type: string
      normalization_context:
        groups:
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'FolderTpl:Expectation'
    periods:
      method: GET
      path: /folder_tpls/{id}/periods
      security: is_granted('ROLE_Dashboard')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Get folder periods'
        parameters:
          - name: fromdate
            in: query
            description: 'beginning of date interval'
            required: false
            type: string
          - name: todate
            in: query
            description: 'end of date interval'
            required: false
            type: string
      normalization_context:
        groups:
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'FolderTpl:Periods'

##################################
App\Entity\Permission:
  attributes:
    denormalization_context:
      groups:
        - 'Permission:Update'

    normalization_context:
      groups:
        - 'Permission:Read'
        - 'Resource'
      preserve_empty_objects: true
      skip_null_values: true

  collectionOperations:
    get:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Folder\FolderTplQuestionnaireTpl:
  attributes:
    denormalization_context:
      groups:
        - 'FolderTplQuestionnaireTpl:Update'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'FolderTplQuestionnaireTpl:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Questionnaire\QuestionnaireTpl:
  attributes:
    denormalization_context:
      groups:
        - 'QuestionnaireTpl:Update'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'QuestionnaireTpl:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
        - 'Score'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
      output: App\Entity\Questionnaire\QuestionnaireTpl
    post:
      method: POST
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
      input: App\Entity\Questionnaire\QuestionnaireTpl

  itemOperations:
    delete:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
      output: App\Entity\Questionnaire\QuestionnaireTpl
    update:
      method: PATCH
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
      input: App\Entity\Questionnaire\QuestionnaireTpl

##################################
App\Entity\Questionnaire\QuestionnaireTplBlockTpl:
  attributes:
    denormalization_context:
      groups:
        - 'QuestionnaireTplBlockTpl:Update'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'QuestionnaireTplBlockTpl:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:

##################################
App\Entity\Block\BlockTpl:
  attributes:
    denormalization_context:
      groups:
        - 'BlockTpl:Update'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'BlockTpl:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
        - 'Score'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_User') or is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'



##################################
App\Entity\Question\QuestionTpl:
  attributes:
    denormalization_context:
      groups:
        - 'QuestionTpl:Update'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'QuestionTpl:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
        - 'Score'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Choice\ChoiceTpl:
  attributes:
    denormalization_context:
      groups:
        - 'ChoiceTpl:Update'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'ChoiceTpl:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_User')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_Admin')
      security_message: 'Sorry, but you are not authorized.'

