version: '3'

volumes:
  mysql_data:
    driver: local

services:
  gotenberg:
    image: thecodingmachine/gotenberg:6
    container_name: cockpit_gotenberg

  mysql:
    image: mysql:5.7
    container_name: cockpit_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak

  keycloak:
    container_name: cockpit_keycloak
    image: quay.io/keycloak/keycloak:9.0.3
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: KPa550rd
      PROXY_ADDRESS_FORWARDING: 'true'
      JDBC_PARAMS: "useSSL=false"
    volumes:
      - /tmp:/tmp
    ports:
      - 8080:8080
    depends_on:
      - mysql
  cockpit:
    image: cockpitlabs/cockpitee:latest
    container_name: cockpit_apps
    environment:
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: root
      DB_USER: cockpit
      DB_PASSWORD: cockpit
      DB_DATABASE: cockpit
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: KPa550rd
      KEYCLOAKREALM: cockpit
      KEYCLOAKCLIENTAUTHURL: http://localhost:8080/auth
      BASEURL: http://localhost
      APIURL: http://localhost/core
      GOTENBERGURL: http://gotenberg:3000
    ports:
      - 80:80
    depends_on:
      - keycloak
      - mysql
      - gotenberg

