#!/usr/bin/env bash

mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD}<<MYSQL_SCRIPT
CREATE DATABASE IF NOT EXISTS cockpit;
CREATE USER IF NOT EXISTS '${COCKPIT_DBUSER}'@'%' IDENTIFIED WITH mysql_native_password BY '${COCKPIT_DBPASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${COCKPIT_DBUSER}'@'%';
FLUSH PRIVILEGES;
MYSQL_SCRIPT
