; conf/php.ini

date.timezone = Europe/Paris

opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.revalidate_freq = 0
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0

upload_max_filesize = 16M
post_max_size = 16M

realpath_cache_size=4096k
realpath_cache_ttl=7200

display_errors = On
display_startup_errors = Off
error_log = /proc/self/fd/2
